"""initial

Revision ID: 1f94a57c611c
Revises:
Create Date: 2026-05-21 03:57:36.803850

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = '1f94a57c611c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fruit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('picture', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('createat', sa.DateTime(), nullable=False),
    sa.Column('deleteat', sa.DateTime(), nullable=True),
    sa.Column('updateat', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fruit_name'), 'fruit', ['name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('surname', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('createat', sa.DateTime(), nullable=False),
    sa.Column('deleteat', sa.DateTime(), nullable=True),
    sa.Column('updateat', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    op.create_table('vegetable',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('picture', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('createat', sa.DateTime(), nullable=False),
    sa.Column('deleteat', sa.DateTime(), nullable=True),
    sa.Column('updateat', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vegetable_name'), 'vegetable', ['name'], unique=False)
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('users_id', sa.Integer(), nullable=False),
    sa.Column('vegetable_id', sa.Integer(), nullable=True),
    sa.Column('fruit_id', sa.Integer(), nullable=True),
    sa.Column('createat', sa.DateTime(), nullable=False),
    sa.Column('deleteat', sa.DateTime(), nullable=True),
    sa.Column('updateat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fruit_id'], ['fruit.id'], ),
    sa.ForeignKeyConstraint(['users_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['vegetable_id'], ['vegetable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite')
    op.drop_index(op.f('ix_vegetable_name'), table_name='vegetable')
    op.drop_table('vegetable')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_fruit_name'), table_name='fruit')
    op.drop_table('fruit')
    # ### end Alembic commands ###
