"""add_nutrition_table

Revision ID: 7cac7cb24d9a
Revises: 1f94a57c611c
Create Date: 2026-05-22 00:18:02.712500

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '7cac7cb24d9a'
down_revision: Union[str, None] = '1f94a57c611c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nutrition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fruit_id', sa.Integer(), nullable=True),
    sa.Column('vegetable_id', sa.Integer(), nullable=True),
    sa.Column('calories', sa.Float(), nullable=True),
    sa.Column('protein', sa.Float(), nullable=True),
    sa.Column('carbs', sa.Float(), nullable=True),
    sa.Column('fat', sa.Float(), nullable=True),
    sa.Column('fiber', sa.Float(), nullable=True),
    sa.Column('createat', sa.DateTime(), nullable=False),
    sa.Column('deleteat', sa.DateTime(), nullable=True),
    sa.Column('updateat', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fruit_id'], ['fruit.id'], ),
    sa.ForeignKeyConstraint(['vegetable_id'], ['vegetable.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nutrition_fruit_id'), 'nutrition', ['fruit_id'], unique=False)
    op.create_index(op.f('ix_nutrition_vegetable_id'), 'nutrition', ['vegetable_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nutrition_vegetable_id'), table_name='nutrition')
    op.drop_index(op.f('ix_nutrition_fruit_id'), table_name='nutrition')
    op.drop_table('nutrition')
    # ### end Alembic commands ###
