"""add_user_verification_fields

Revision ID: a10c6446c983
Revises: 7cac7cb24d9a
Create Date: 2026-05-22 00:44:24.992328

"""
from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel
from alembic import op

revision: str = 'a10c6446c983'
down_revision: Union[str, None] = '7cac7cb24d9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_verified', sa.Boolean(), nullable=False, server_default=sa.text("0")))  # noqa: E501
    op.add_column('users', sa.Column('verify_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))  # noqa: E501
    op.add_column('users', sa.Column('reset_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))  # noqa: E501
    op.add_column('users', sa.Column('reset_token_expires', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reset_token_expires')
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'verify_token')
    op.drop_column('users', 'is_verified')
    # ### end Alembic commands ###
